module.exports = {
    // EMOJIS SETTINGS //
    tick: "✅",
    diamond: "💎",
    clock: "⏰",
    sheild: "🛡️",
    key: "🔑",
    bell: "🛎️",
    hammer: "🔨",
    lock: "🔒",
    love: "💘",
    status: "📩",
    sparkles: "✨",
    location: "🔦",
    rocket: "🚀",
    book: "📓",
    bot: "🤖",
    loading: "🔄",
    happy: "😄",
    wave: "🖐",
    owner: "👑",
    bin: "🗑️",
    star: "⭐",
    channel: "📜",
    error: "❌",
    clipboard: "📋",
}